/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.demomillicom;

import java.awt.BorderLayout;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLConnection;
import java.nio.charset.Charset;
import javax.swing.*;
import java.awt.BorderLayout;
import java.awt.FlowLayout;


/**
 *
 * @author juan
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        lectura_json();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdInicio = new javax.swing.JButton();
        cmdFin = new javax.swing.JButton();
        cmdSiguiente = new javax.swing.JButton();
        cmdAnterior = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmdInicio.setText("Inicio");

        cmdFin.setText("Fin");

        cmdSiguiente.setText("Siguiente");

        cmdAnterior.setText("Anterior");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(cmdInicio)
                .addGap(18, 18, 18)
                .addComponent(cmdAnterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdSiguiente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmdFin)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdInicio)
                    .addComponent(cmdSiguiente)
                    .addComponent(cmdAnterior)
                    .addComponent(cmdFin))
                .addContainerGap(471, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lectura_json() throws IOException{
        URL v_url = new URL("https://xkcd.com/info.0.json");
         BufferedReader v_br = new BufferedReader(new         
         InputStreamReader(v_url.openStream(),
         Charset.forName("UTF-8")));
         String v_linea = " ";
         StringBuilder jsonString = new StringBuilder();
         while((v_linea = v_br.readLine()) != null){
           jsonString.append(v_linea);
         }
         
         String[] a_tag = String.valueOf(jsonString).split(","); 
  
         getContentPane().setLayout(new BorderLayout());
         
         //getContentPane().add(new JLabel("<table><tr><td>hola</td><td>chao</td></tr></table></html>"));
         
         String v_tabla = "<html>";
         
         for (String v_tag : a_tag) {
             String[] a_campo = v_tag.replace("\"","").split(":"); 
             
             if (a_campo.length == 1){
                v_tabla += "<tr><td></td>";
                v_tabla += "<td></td>";
                v_tabla += "<td>" + String.valueOf(a_campo[0]) + "</td></tr>";
             } else {
                v_tabla += "<tr><td>" + String.valueOf(a_campo[0]) + "</td>";
                v_tabla += "<td>:</td>";
                if (String.valueOf(a_campo[0]).indexOf("img")>0){
                    v_tabla += "<td><img src='" + String.valueOf(a_campo[1]) + ":" + String.valueOf(a_campo[2]) + "' width='300' height='300'></td></tr>";
                } else {
                    v_tabla += "<td>" + String.valueOf(a_campo[1]) + "</td></tr>";
                }
             }
            
         }
         v_tabla += "</html>";
         getContentPane().add(new JLabel(v_tabla));
         setVisible( true );

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
                
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAnterior;
    private javax.swing.JButton cmdFin;
    private javax.swing.JButton cmdInicio;
    private javax.swing.JButton cmdSiguiente;
    // End of variables declaration//GEN-END:variables

}
